### ISSUE TITLE
Notify via email of preview job failures

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/preview-action#44]
We should send an email if a pipeline fails because of a bug in the Uffizzi CLI or platform API. We should do this within the preview action reusable workflow if possible or at least create an example workflow job that we can include in PRs to projects. See [this example](https://www.ravsam.in/blog/send-email-notification-when-github-action-fails/).  

We should only send emails if the failure occurred in one of the Uffizzi jobs/steps. Send the email to support@uffizzi.com.

**Comment by gadkins** [comment]
We should only send emails if the failure occurred in one of the Uffizzi jobs/steps

**Comment by antlu** [comment]
It turned out that repository secrets are not readable by a reusable workflow if they are set in the same repository as the workflow. The secrets must be [passed from a caller workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow). A solution would be letting workflow users provide credentials for their own mail sender if they want to receive such error notifications, but I doubt we want this.

**Comment by moklidia** [comment]
Will implement by sending errors to Sentry from CLI
